import { FloorPlanJSON } from './planSchema';

export const BRIGADE_INSIGNIA_FIXTURE: FloorPlanJSON = {
  projectId: 'brigade-insignia-5bhk-duplex-l1',
  metadata: {
    propertyName: 'Brigade Insignia',
    layoutType: '5 BHK Duplex • Type L1',
    superBuiltUpAreaSqFt: 5827,
    reraCarpetAreaSqFt: 3582.26,
    balconyCarpetAreaSqFt: 681.36,
    numFloors: 2,
    builder: 'Brigade Group',
    towerBlock: 'Block C',
    floorNumber: '14th Floor (Duplex)',
    orientation: 'North-East Facing Entry',
  },
  analysisTimestamp: '2026-09-16T17:00:00Z',
  confidenceScore: 0.98,
  ambiguities: [],
  isApprovedByUsers: true,
  floors: {
    lower: {
      floorKey: 'lower',
      floorName: 'DX - LOWER FLOOR (TYPE L1)',
      sourceImageUrl: '/fixtures/brigade_insignia_lower_plan.jpg',
      renderImageUrl: '/fixtures/brigade_insignia_lower_3d.jpg',
      entrances: [[0.65, 0.18]],
      floorConnections: ['ST -> Upper Stair Landing ST2'],
      stairs: [
        {
          id: 'ST1',
          polygon: [[0.28, 0.32], [0.46, 0.32], [0.46, 0.44], [0.28, 0.44]],
          direction: 'up',
          risesTowards: 'upper-right',
          flightType: 'u-shaped',
        },
      ],
      voids: [],
      rooms: [
        {
          id: 'r_f',
          code: 'F',
          name: 'Foyer',
          type: 'foyer',
          polygon: [[0.62, 0.15], [0.75, 0.15], [0.75, 0.22], [0.62, 0.22]],
          dimensions: "8'7\" × 5'5\"",
          calculatedSqFt: 46,
          isCarpetArea: false,
          floorKey: 'lower',
          doors: [{ id: 'd_f', position: [0.65, 0.15], swingDirection: 'inward' }],
          windows: [],
          furniture: [{ id: 'f_console', type: 'counter', position: [0.68, 0.18], label: 'Console Table' }],
        },
        {
          id: 'r_lr',
          code: 'LR',
          name: 'Formal Living',
          type: 'living',
          polygon: [[0.32, 0.15], [0.62, 0.15], [0.62, 0.31], [0.32, 0.31]],
          dimensions: "25'10\" × 14'0\"",
          calculatedSqFt: 359,
          isCarpetArea: false,
          floorKey: 'lower',
          doors: [{ id: 'd_blr', position: [0.32, 0.23], swingDirection: 'sliding' }],
          windows: [{ id: 'w_lr', position: [0.32, 0.20], width: 0.1 }],
          furniture: [
            { id: 'f_sofa', type: 'sofa', position: [0.45, 0.22], label: 'L-Shaped Sectional' },
            { id: 'f_tv', type: 'tv_unit', position: [0.58, 0.22], label: 'Media Credenza' },
          ],
        },
        {
          id: 'r_din',
          code: 'DIN',
          name: 'Dining',
          type: 'dining',
          polygon: [[0.46, 0.31], [0.62, 0.31], [0.62, 0.44], [0.46, 0.44]],
          dimensions: "13'1\" × 7'4\"",
          calculatedSqFt: 96,
          isCarpetArea: false,
          floorKey: 'lower',
          doors: [],
          windows: [],
          furniture: [{ id: 'f_dtable', type: 'dining_table', position: [0.54, 0.37], label: '8-Seater Dining Table' }],
        },
        {
          id: 'r_kit',
          code: 'KIT',
          name: 'Kitchen',
          type: 'kitchen',
          polygon: [[0.62, 0.22], [0.76, 0.22], [0.76, 0.38], [0.62, 0.38]],
          dimensions: "8'0\" × 15'5\"",
          calculatedSqFt: 124,
          isCarpetArea: false,
          floorKey: 'lower',
          doors: [{ id: 'd_kit', position: [0.62, 0.28] }],
          windows: [{ id: 'w_kit', position: [0.76, 0.30] }],
          furniture: [{ id: 'f_kcounter', type: 'counter', position: [0.69, 0.30], label: 'Granite Countertop' }],
        },
        {
          id: 'r_ut',
          code: 'UT',
          name: 'Utility',
          type: 'utility',
          polygon: [[0.62, 0.38], [0.78, 0.38], [0.78, 0.46], [0.62, 0.46]],
          dimensions: "11'6\" × 4'11\"",
          calculatedSqFt: 57,
          isCarpetArea: false,
          floorKey: 'lower',
          doors: [{ id: 'd_ut', position: [0.62, 0.40] }],
          windows: [{ id: 'w_ut', position: [0.78, 0.42] }],
          furniture: [],
        },
        {
          id: 'r_mr',
          code: 'MR',
          name: "Maid's Room",
          type: 'maid',
          polygon: [[0.76, 0.22], [0.90, 0.22], [0.90, 0.35], [0.76, 0.35]],
          dimensions: "7'7\" × 9'4\"",
          calculatedSqFt: 71,
          isCarpetArea: false,
          floorKey: 'lower',
          doors: [{ id: 'd_mr', position: [0.76, 0.26] }],
          windows: [{ id: 'w_mr', position: [0.90, 0.28] }],
          furniture: [{ id: 'f_mbed', type: 'bed', position: [0.83, 0.28] }],
        },
        {
          id: 'r_mt',
          code: 'MT',
          name: "Maid's Toilet",
          type: 'toilet',
          polygon: [[0.78, 0.35], [0.90, 0.35], [0.90, 0.44], [0.78, 0.44]],
          dimensions: "4'1\" × 5'5\"",
          calculatedSqFt: 22,
          isCarpetArea: false,
          floorKey: 'lower',
          doors: [{ id: 'd_mt', position: [0.78, 0.38] }],
          windows: [],
          furniture: [{ id: 'f_sanitary_mt', type: 'sanitary', position: [0.84, 0.39] }],
        },
        {
          id: 'r_pr',
          code: 'PR',
          name: 'Powder Room',
          type: 'powder',
          polygon: [[0.46, 0.44], [0.55, 0.44], [0.55, 0.52], [0.46, 0.52]],
          dimensions: "5'5\" × 4'11\"",
          calculatedSqFt: 27,
          isCarpetArea: false,
          floorKey: 'lower',
          doors: [{ id: 'd_pr', position: [0.50, 0.44] }],
          windows: [],
          furniture: [{ id: 'f_wc_pr', type: 'sanitary', position: [0.50, 0.48] }],
        },
        {
          id: 'r_st',
          code: 'ST',
          name: 'Stair Hall',
          type: 'stair',
          polygon: [[0.28, 0.32], [0.46, 0.32], [0.46, 0.44], [0.28, 0.44]],
          dimensions: "14'6\" × 12'3\"",
          calculatedSqFt: 177,
          isCarpetArea: false,
          floorKey: 'lower',
          doors: [],
          windows: [],
          furniture: [],
        },
        {
          id: 'r_ml',
          code: 'ML',
          name: 'Master Lobby',
          type: 'lobby',
          polygon: [[0.36, 0.44], [0.46, 0.44], [0.46, 0.62], [0.36, 0.62]],
          dimensions: "8'11\" × 13'2\"",
          calculatedSqFt: 117,
          isCarpetArea: false,
          floorKey: 'lower',
          doors: [],
          windows: [],
          furniture: [],
        },
        {
          id: 'r_br1',
          code: 'BR1',
          name: 'Primary / Master Bedroom',
          type: 'bedroom',
          polygon: [[0.36, 0.62], [0.55, 0.62], [0.55, 0.82], [0.36, 0.82]],
          dimensions: "18'3\" × 13'0\"",
          calculatedSqFt: 236,
          isCarpetArea: false,
          floorKey: 'lower',
          doors: [{ id: 'd_br1', position: [0.42, 0.62] }],
          windows: [{ id: 'w_br1', position: [0.45, 0.82] }],
          furniture: [
            { id: 'f_kingbed', type: 'bed', position: [0.45, 0.72], label: 'King Bed Headboard' },
            { id: 'f_nightstand', type: 'counter', position: [0.38, 0.72] },
          ],
        },
        {
          id: 'r_d1',
          code: 'D1',
          name: 'Master Dress',
          type: 'dress',
          polygon: [[0.46, 0.52], [0.55, 0.52], [0.55, 0.62], [0.46, 0.62]],
          dimensions: "9'0\" × 5'5\"",
          calculatedSqFt: 49,
          isCarpetArea: false,
          floorKey: 'lower',
          doors: [{ id: 'd_d1', position: [0.50, 0.62] }],
          windows: [],
          furniture: [{ id: 'f_w1', type: 'wardrobe', position: [0.50, 0.57] }],
        },
        {
          id: 'r_t1',
          code: 'T1',
          name: 'Master Toilet',
          type: 'toilet',
          polygon: [[0.22, 0.44], [0.36, 0.44], [0.36, 0.68], [0.22, 0.68]],
          dimensions: "9'0\" × 12'8\"",
          calculatedSqFt: 114,
          isCarpetArea: false,
          floorKey: 'lower',
          doors: [{ id: 'd_t1', position: [0.36, 0.55] }],
          windows: [{ id: 'w_t1', position: [0.22, 0.56] }],
          furniture: [
            { id: 'f_vanity', type: 'sanitary', position: [0.29, 0.48], label: 'Double Vanity' },
            { id: 'f_shower', type: 'sanitary', position: [0.29, 0.62], label: 'Glass Shower Cubicle' },
          ],
        },
        {
          id: 'r_br2',
          code: 'BR2',
          name: 'Bedroom 2',
          type: 'bedroom',
          polygon: [[0.32, 0.02], [0.52, 0.02], [0.52, 0.15], [0.32, 0.15]],
          dimensions: "17'1\" × 12'1\"",
          calculatedSqFt: 205,
          isCarpetArea: false,
          floorKey: 'lower',
          doors: [{ id: 'd_br2', position: [0.42, 0.15] }],
          windows: [{ id: 'w_br2', position: [0.42, 0.02] }],
          furniture: [{ id: 'f_bed2', type: 'bed', position: [0.42, 0.08] }],
        },
        {
          id: 'r_d2',
          code: 'D2',
          name: 'Bedroom 2 Dress',
          type: 'dress',
          polygon: [[0.52, 0.02], [0.60, 0.02], [0.60, 0.15], [0.52, 0.15]],
          dimensions: "9'7\" × 5'8\"",
          calculatedSqFt: 54,
          isCarpetArea: false,
          floorKey: 'lower',
          doors: [],
          windows: [],
          furniture: [{ id: 'f_w2', type: 'wardrobe', position: [0.56, 0.08] }],
        },
        {
          id: 'r_t2',
          code: 'T2',
          name: 'Bedroom 2 Toilet',
          type: 'toilet',
          polygon: [[0.60, 0.02], [0.72, 0.02], [0.72, 0.15], [0.60, 0.15]],
          dimensions: "9'0\" × 6'1\"",
          calculatedSqFt: 55,
          isCarpetArea: false,
          floorKey: 'lower',
          doors: [{ id: 'd_t2', position: [0.60, 0.10] }],
          windows: [{ id: 'w_t2', position: [0.66, 0.02] }],
          furniture: [{ id: 'f_t2_fix', type: 'sanitary', position: [0.66, 0.08] }],
        },
        {
          id: 'r_b1',
          code: 'B1',
          name: 'Master Balcony',
          type: 'balcony',
          polygon: [[0.22, 0.68], [0.36, 0.68], [0.36, 0.88], [0.22, 0.88]],
          dimensions: "8'10\" × 13'0\"",
          calculatedSqFt: 114,
          isCarpetArea: false,
          floorKey: 'lower',
          doors: [{ id: 'd_b1', position: [0.36, 0.78], swingDirection: 'sliding' }],
          windows: [],
          furniture: [{ id: 'f_planter1', type: 'lounger', position: [0.29, 0.78], label: 'Outdoor Armchairs' }],
        },
        {
          id: 'r_sb1',
          code: 'SB1',
          name: 'Standing Balcony',
          type: 'standing_balcony',
          polygon: [[0.55, 0.62], [0.59, 0.62], [0.59, 0.82], [0.55, 0.82]],
          dimensions: "10'11\" × 2'0\"",
          calculatedSqFt: 21,
          isCarpetArea: false,
          floorKey: 'lower',
          doors: [],
          windows: [],
          furniture: [],
        },
        {
          id: 'r_b2',
          code: 'B2',
          name: 'Bedroom 2 Balcony',
          type: 'balcony',
          polygon: [[0.22, 0.02], [0.32, 0.02], [0.32, 0.15], [0.22, 0.15]],
          dimensions: "5'6\" × 8'7\"",
          calculatedSqFt: 47,
          isCarpetArea: false,
          floorKey: 'lower',
          doors: [{ id: 'd_b2', position: [0.32, 0.08], swingDirection: 'sliding' }],
          windows: [],
          furniture: [],
        },
        {
          id: 'r_blr',
          code: 'BLR',
          name: 'Living Balcony',
          type: 'balcony',
          polygon: [[0.20, 0.15], [0.32, 0.15], [0.32, 0.32], [0.20, 0.32]],
          dimensions: "6'3\" × 14'3\"",
          calculatedSqFt: 89,
          isCarpetArea: false,
          floorKey: 'lower',
          doors: [{ id: 'd_blr_in', position: [0.32, 0.24], swingDirection: 'sliding' }],
          windows: [],
          furniture: [{ id: 'f_bchairs', type: 'lounger', position: [0.26, 0.23], label: 'Teak Deck Chairs' }],
        },
      ],
    },
    upper: {
      floorKey: 'upper',
      floorName: 'DX - UPPER FLOOR (TYPE L1)',
      sourceImageUrl: '/fixtures/brigade_insignia_upper_plan.jpg',
      renderImageUrl: '/fixtures/brigade_insignia_upper_3d.jpg',
      entrances: [],
      floorConnections: ['ST2 -> Lower Stair Hall ST'],
      stairs: [
        {
          id: 'ST2',
          polygon: [[0.28, 0.32], [0.46, 0.32], [0.46, 0.44], [0.28, 0.44]],
          direction: 'down',
          risesTowards: 'lower-right',
          flightType: 'u-shaped',
        },
      ],
      voids: [
        {
          id: 'vb1',
          polygon: [[0.20, 0.15], [0.32, 0.15], [0.32, 0.32], [0.20, 0.32]],
          label: 'VB',
          description: 'Void / Balcony Below',
        },
      ],
      rooms: [
        {
          id: 'r_f2',
          code: 'F2',
          name: 'Upper Foyer',
          type: 'foyer',
          polygon: [[0.62, 0.15], [0.75, 0.15], [0.75, 0.22], [0.62, 0.22]],
          dimensions: "8'7\" × 5'5\"",
          calculatedSqFt: 46,
          isCarpetArea: false,
          floorKey: 'upper',
          doors: [],
          windows: [],
          furniture: [],
        },
        {
          id: 'r_fl',
          code: 'FL',
          name: 'Family Lounge',
          type: 'living',
          polygon: [[0.46, 0.15], [0.62, 0.15], [0.62, 0.44], [0.46, 0.44]],
          dimensions: "13'1\" × 21'4\"",
          calculatedSqFt: 280,
          isCarpetArea: false,
          floorKey: 'upper',
          doors: [{ id: 'd_fb', position: [0.46, 0.20], swingDirection: 'sliding' }],
          windows: [],
          furniture: [
            { id: 'f_fl_sofa', type: 'sofa', position: [0.54, 0.28], label: 'Comfort Sofa' },
            { id: 'f_fl_tv', type: 'tv_unit', position: [0.54, 0.38], label: 'Lounge Console' },
          ],
        },
        {
          id: 'r_pr2',
          code: 'PR2',
          name: 'Powder Room',
          type: 'powder',
          polygon: [[0.46, 0.44], [0.55, 0.44], [0.55, 0.52], [0.46, 0.52]],
          dimensions: "5'5\" × 4'11\"",
          calculatedSqFt: 27,
          isCarpetArea: false,
          floorKey: 'upper',
          doors: [{ id: 'd_pr2', position: [0.50, 0.44] }],
          windows: [],
          furniture: [{ id: 'f_wc_pr2', type: 'sanitary', position: [0.50, 0.48] }],
        },
        {
          id: 'r_st2_room',
          code: 'ST2',
          name: 'Stair Landing',
          type: 'stair',
          polygon: [[0.28, 0.32], [0.46, 0.32], [0.46, 0.44], [0.28, 0.44]],
          dimensions: 'NR',
          calculatedSqFt: 'NR',
          isCarpetArea: false,
          floorKey: 'upper',
          doors: [],
          windows: [],
          furniture: [],
        },
        {
          id: 'r_l3',
          code: 'L3',
          name: 'Bedroom 3 Lobby',
          type: 'lobby',
          polygon: [[0.36, 0.44], [0.46, 0.44], [0.46, 0.62], [0.36, 0.62]],
          dimensions: "8'11\" × 13'2\"",
          calculatedSqFt: 117,
          isCarpetArea: false,
          floorKey: 'upper',
          doors: [],
          windows: [],
          furniture: [],
        },
        {
          id: 'r_br3',
          code: 'BR3',
          name: 'Bedroom 3',
          type: 'bedroom',
          polygon: [[0.36, 0.62], [0.55, 0.62], [0.55, 0.82], [0.36, 0.82]],
          dimensions: "18'3\" × 13'0\"",
          calculatedSqFt: 236,
          isCarpetArea: false,
          floorKey: 'upper',
          doors: [{ id: 'd_br3', position: [0.42, 0.62] }],
          windows: [{ id: 'w_br3', position: [0.45, 0.82] }],
          furniture: [{ id: 'f_bed3', type: 'bed', position: [0.45, 0.72], label: 'Queen Bed' }],
        },
        {
          id: 'r_d3',
          code: 'D3',
          name: 'Bedroom 3 Dress',
          type: 'dress',
          polygon: [[0.46, 0.52], [0.55, 0.52], [0.55, 0.62], [0.46, 0.62]],
          dimensions: "9'0\" × 5'5\"",
          calculatedSqFt: 49,
          isCarpetArea: false,
          floorKey: 'upper',
          doors: [{ id: 'd_d3', position: [0.50, 0.62] }],
          windows: [],
          furniture: [{ id: 'f_w3', type: 'wardrobe', position: [0.50, 0.57] }],
        },
        {
          id: 'r_t3',
          code: 'T3',
          name: 'Bedroom 3 Toilet',
          type: 'toilet',
          polygon: [[0.22, 0.44], [0.36, 0.44], [0.36, 0.68], [0.22, 0.68]],
          dimensions: "9'0\" × 12'8\"",
          calculatedSqFt: 114,
          isCarpetArea: false,
          floorKey: 'upper',
          doors: [{ id: 'd_t3', position: [0.36, 0.55] }],
          windows: [{ id: 'w_t3', position: [0.22, 0.56] }],
          furniture: [{ id: 'f_t3_fix', type: 'sanitary', position: [0.29, 0.55] }],
        },
        {
          id: 'r_br4',
          code: 'BR4',
          name: 'Bedroom 4',
          type: 'bedroom',
          polygon: [[0.62, 0.22], [0.76, 0.22], [0.76, 0.38], [0.62, 0.38]],
          dimensions: "10'3\" × 15'5\"",
          calculatedSqFt: 160,
          isCarpetArea: false,
          floorKey: 'upper',
          doors: [{ id: 'd_br4', position: [0.62, 0.30] }],
          windows: [{ id: 'w_br4', position: [0.76, 0.30] }],
          furniture: [{ id: 'f_bed4', type: 'bed', position: [0.69, 0.30] }],
        },
        {
          id: 'r_d4',
          code: 'D4',
          name: 'Bedroom 4 Dress',
          type: 'dress',
          polygon: [[0.76, 0.22], [0.84, 0.22], [0.84, 0.32], [0.76, 0.32]],
          dimensions: "5'9\" × 6'1\"",
          calculatedSqFt: 35,
          isCarpetArea: false,
          floorKey: 'upper',
          doors: [],
          windows: [],
          furniture: [{ id: 'f_w4', type: 'wardrobe', position: [0.80, 0.27] }],
        },
        {
          id: 'r_t4',
          code: 'T4',
          name: 'Bedroom 4 Toilet',
          type: 'toilet',
          polygon: [[0.76, 0.32], [0.84, 0.32], [0.84, 0.44], [0.76, 0.44]],
          dimensions: "5'5\" × 9'0\"",
          calculatedSqFt: 49,
          isCarpetArea: false,
          floorKey: 'upper',
          doors: [{ id: 'd_t4', position: [0.76, 0.38] }],
          windows: [{ id: 'w_t4', position: [0.84, 0.38] }],
          furniture: [{ id: 'f_t4_fix', type: 'sanitary', position: [0.80, 0.38] }],
        },
        {
          id: 'r_br5',
          code: 'BR5',
          name: 'Bedroom 5',
          type: 'bedroom',
          polygon: [[0.32, 0.02], [0.52, 0.02], [0.52, 0.15], [0.32, 0.15]],
          dimensions: "17'1\" × 12'1\"",
          calculatedSqFt: 205,
          isCarpetArea: false,
          floorKey: 'upper',
          doors: [{ id: 'd_br5', position: [0.42, 0.15] }],
          windows: [{ id: 'w_br5', position: [0.42, 0.02] }],
          furniture: [{ id: 'f_bed5', type: 'bed', position: [0.42, 0.08] }],
        },
        {
          id: 'r_d5',
          code: 'D5',
          name: 'Bedroom 5 Dress',
          type: 'dress',
          polygon: [[0.52, 0.02], [0.60, 0.02], [0.60, 0.15], [0.52, 0.15]],
          dimensions: "9'7\" × 5'8\"",
          calculatedSqFt: 54,
          isCarpetArea: false,
          floorKey: 'upper',
          doors: [],
          windows: [],
          furniture: [{ id: 'f_w5', type: 'wardrobe', position: [0.56, 0.08] }],
        },
        {
          id: 'r_t5',
          code: 'T5',
          name: 'Bedroom 5 Toilet',
          type: 'toilet',
          polygon: [[0.60, 0.02], [0.72, 0.02], [0.72, 0.15], [0.60, 0.15]],
          dimensions: "9'0\" × 6'1\"",
          calculatedSqFt: 55,
          isCarpetArea: false,
          floorKey: 'upper',
          doors: [{ id: 'd_t5', position: [0.60, 0.10] }],
          windows: [{ id: 'w_t5', position: [0.66, 0.02] }],
          furniture: [{ id: 'f_t5_fix', type: 'sanitary', position: [0.66, 0.08] }],
        },
        {
          id: 'r_fb',
          code: 'FB',
          name: 'Family Balcony',
          type: 'balcony',
          polygon: [[0.32, 0.15], [0.46, 0.15], [0.46, 0.32], [0.32, 0.32]],
          dimensions: "12'2\" × 14'0\"",
          calculatedSqFt: 171,
          isCarpetArea: false,
          floorKey: 'upper',
          doors: [{ id: 'd_fb_door', position: [0.46, 0.20], swingDirection: 'sliding' }],
          windows: [],
          furniture: [{ id: 'f_fb_furniture', type: 'lounger', position: [0.39, 0.23], label: 'Outdoor Lounge Seating' }],
        },
        {
          id: 'r_vb',
          code: 'VB',
          name: 'Void / Balcony Below',
          type: 'void',
          polygon: [[0.20, 0.15], [0.32, 0.15], [0.32, 0.32], [0.20, 0.32]],
          dimensions: 'NR',
          calculatedSqFt: 'NR',
          isCarpetArea: false,
          floorKey: 'upper',
          doors: [],
          windows: [],
          furniture: [],
        },
        {
          id: 'r_b3',
          code: 'B3',
          name: 'Bedroom 3 Balcony',
          type: 'balcony',
          polygon: [[0.22, 0.68], [0.36, 0.68], [0.36, 0.88], [0.22, 0.88]],
          dimensions: "4'11\" × 13'0\"",
          calculatedSqFt: 63,
          isCarpetArea: false,
          floorKey: 'upper',
          doors: [{ id: 'd_b3', position: [0.36, 0.78], swingDirection: 'sliding' }],
          windows: [],
          furniture: [],
        },
        {
          id: 'r_sb3',
          code: 'SB3',
          name: 'Standing Balcony',
          type: 'standing_balcony',
          polygon: [[0.55, 0.62], [0.59, 0.62], [0.59, 0.82], [0.55, 0.82]],
          dimensions: "10'11\" × 2'0\"",
          calculatedSqFt: 21,
          isCarpetArea: false,
          floorKey: 'upper',
          doors: [],
          windows: [],
          furniture: [],
        },
        {
          id: 'r_b4',
          code: 'B4',
          name: 'Bedroom 4 Balcony',
          type: 'balcony',
          polygon: [[0.62, 0.38], [0.76, 0.38], [0.76, 0.46], [0.62, 0.46]],
          dimensions: "11'6\" × 4'11\"",
          calculatedSqFt: 57,
          isCarpetArea: false,
          floorKey: 'upper',
          doors: [{ id: 'd_b4', position: [0.69, 0.38], swingDirection: 'sliding' }],
          windows: [],
          furniture: [],
        },
        {
          id: 'r_b5',
          code: 'B5',
          name: 'Bedroom 5 Balcony',
          type: 'balcony',
          polygon: [[0.22, 0.02], [0.32, 0.02], [0.32, 0.15], [0.22, 0.15]],
          dimensions: "5'5\" × 7'11\"",
          calculatedSqFt: 43,
          isCarpetArea: false,
          floorKey: 'upper',
          doors: [{ id: 'd_b5', position: [0.32, 0.08], swingDirection: 'sliding' }],
          windows: [],
          furniture: [],
        },
      ],
    },
  },
};
